In [1]:
install.packages("pacman")
suppressPackageStartupMessages(library(pacman))
suppressPackageStartupMessages(p_load(foreach))
suppressPackageStartupMessages(p_load(parallel))
suppressPackageStartupMessages(p_load(data.table))
suppressPackageStartupMessages(p_load(plyr))
suppressPackageStartupMessages(p_load(dplyr))
suppressPackageStartupMessages(p_load(docstring))
suppressPackageStartupMessages(p_load(decoupleR))
suppressPackageStartupMessages(p_load(this.path))
suppressPackageStartupMessages(p_load(ggpubr))

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘iterators’



foreach installed

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)


plyr installed

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)


docstring installed

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message:
“package ‘decoupleR’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages”
Warning message:
“'BiocManager' not available.  Could not check Bioconductor.

Please use `install.packages('BiocManager')` and then retry.”
Warning message in p_install(package, character.only = TRUE, ...):
“”
Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘decoupleR’”
Warning message in p_load(decoupleR):
“Failed to install/load:
decoupleR”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)


this.path installed

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘colorspace’, ‘fracdiff’, ‘lmtest’, ‘timeDate’, ‘urca’, ‘zoo’, ‘RcppArmadillo’, ‘Deriv’, ‘forecast’, ‘microbenchmark’, ‘rbibutils’, ‘numDeriv’, ‘doBy’, ‘SparseM’, ‘MatrixModels’, ‘minqa’, ‘nloptr’, ‘reformulas’, ‘Rdpack’, ‘RcppEigen’, ‘carData’, ‘abind’, ‘Formula’, ‘pbkrtest’, ‘quantreg’, ‘lme4’, ‘corrplot’, ‘car’, ‘ggrepel’, ‘ggsci’, ‘cowplot’, ‘ggsignif’, ‘gridExtra’, ‘polynom’, ‘rstatix’



ggpubr installed

In [2]:
# Initialization parallelism
num.cores <- detectCores()
if(!is.na(num.cores) && (num.cores > 1)) {
  suppressPackageStartupMessages(p_load("doMC"))
  cat(paste("Registering ", num.cores-1, " cores.\n", sep=""))
  registerDoMC(cores=(num.cores-1))
}

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)


doMC installed

Registering 1 cores.

In [3]:
getwd()

[1] "/content"

In [4]:
# Read in CHOOSE scRNA-seq data and metadata
fread_with_rownames <- function(file) {
  tbl <- as.data.frame(fread(file))
  rownames(tbl) <- tbl$V1
  tbl <- tbl[, !(colnames(tbl) == "V1")]
  tbl
}

In [5]:
# sc.metadata.file <- paste0(resources.dir, "CHOOSE-sc-wt-and-tf-metadata.csv")
# sc.data.file <- paste0(resources.dir, "CHOOSE-sc-wt-and-tf-log-norm.csv.gz")
sc.metadata.file <- "/content/CHOOSE-scRNA-seq/CHOOSE-sc-wt-and-tf-metadata.csv"
sc.data.file <- "/content/CHOOSE-scRNA-seq/CHOOSE-sc-wt-and-tf-log-norm.csv.gz"

In [6]:
grnboost2.res.file <- "/content/resources/postprocessed-grnboost2-all-tfs-celltypes-global-var-genes.csv.gz"
tfs.to.analyze.file <- "/content/resources/CHOOSE-tf-to-analyze-metadata.csv"

In [7]:
install.packages('R.utils')
library (R.utils)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘R.oo’, ‘R.methodsS3’


Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.


Attaching package: ‘R.oo’


The following object is masked from ‘package:R.methodsS3’:

    throw


The following objects are masked from ‘package:methods’:

    getClasses, getMethods


The following objects are masked from ‘package:base’:

    attach, detach, load, save


R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.


Attaching package: ‘R.utils’


The following object is masked from ‘package:utils’:

    timestamp


The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings

In [8]:
# Load in predictions to be evaluated. Here from GRNBoost2
grnboost2.res <- as.data.frame(fread(grnboost2.res.file))

In [9]:
grnboost2.res

       cell.type TF    target      importance cor.p        score
1      ctx_ex    ADNP  A1BG        4.8122063  -0.015346043 -0.20630820
2      ctx_ex    ADNP  A1BG-AS1    5.1313537   0.067868789  0.21999064
3      ctx_ex    ADNP  A2ML1-AS1   1.2680347  -0.018052659 -0.05436300
4      ctx_ex    ADNP  AACS        2.5042994  -0.095445500 -0.10736396
5      ctx_ex    ADNP  AADAT       1.1461038  -0.015701855 -0.04913559
6      ctx_ex    ADNP  AAGAB       1.2483417  -0.063810528 -0.05351872
7      ctx_ex    ADNP  AAK1        3.4893503  -0.023517662 -0.14959491
8      ctx_ex    ADNP  AAMDC       2.9492719   0.066225887  0.12644075
9      ctx_ex    ADNP  AAMP        1.3233181  -0.061903056 -0.05673310
10     ctx_ex    ADNP  AAR2        3.6181582  -0.151041228 -0.15511715
11     ctx_ex    ADNP  AARD        1.5251056   0.014720916  0.06538410
12     ctx_ex    ADNP  AARS1       2.3178934   0.163692555  0.09937239
13     ctx_ex    ADNP  AARS2       0.9741241   0.021491357  0.04176251
14     ctx_ex    ADNP  AASDHPPT    2.1410077   0.056925233  0.09178897
15     ctx_ex    ADNP  ABAT        2.0519587  -0.028329788 -0.08797127
16     ctx_ex    ADNP  ABCA1       1.2630468  -0.043398872 -0.05414916
17     ctx_ex    ADNP  ABCA3       2.7114926  -0.074261480 -0.11624671
18     ctx_ex    ADNP  ABCA5       1.2524525   0.059706591  0.05369496
19     ctx_ex    ADNP  ABCA7       1.6180454   0.050869409  0.06936861
20     ctx_ex    ADNP  ABCA8       4.7571808  -0.013374861 -0.20394915
21     ctx_ex    ADNP  ABCB1       0.6285678   0.119528437  0.02694787
22     ctx_ex    ADNP  ABCB11      4.3468354  -0.013156491 -0.18635689
23     ctx_ex    ADNP  ABCB4       1.4531479  -0.021129328 -0.06229914
24     ctx_ex    ADNP  ABCB5       2.6961369   0.087742822  0.11558838
25     ctx_ex    ADNP  ABCB8       2.1651409   0.003921414  0.09282360
26     ctx_ex    ADNP  ABCC1       1.8396807   0.132420833  0.07887052
27     ctx_ex    ADNP  ABCC4       1.6461554   0.039393546  0.07057373
28     ctx_ex    ADNP  ABCC9       0.8599288   0.006783037  0.03686674
29     ctx_ex    ADNP  ABCD2       1.7530739  -0.004223639 -0.07515753
30     ctx_ex    ADNP  ABCD3       1.6523321   0.105793431  0.07083854
⋮      ⋮         ⋮     ⋮           ⋮          ⋮            ⋮
654661 ge_npc    TCF20 ZPBP        0.7581790  -0.071054819 -0.03250454
654662 ge_npc    TCF20 ZPR1        5.3615271   0.051412345  0.22985860
654663 ge_npc    TCF20 ZRANB1      2.7465419   0.142805376  0.11774934
654664 ge_npc    TCF20 ZRANB2-AS1  1.4177724  -0.025564550 -0.06078253
654665 ge_npc    TCF20 ZRANB3      2.3970258   0.083831619  0.10276494
654666 ge_npc    TCF20 ZRSR2       1.8171155   0.031987701  0.07790311
654667 ge_npc    TCF20 ZSCAN12     5.4132078   0.068765795  0.23207425
654668 ge_npc    TCF20 ZSCAN16     1.3666839   0.110558602  0.05859227
654669 ge_npc    TCF20 ZSCAN16-AS1 2.6334478  -0.146168043 -0.11290079
654670 ge_npc    TCF20 ZSCAN18     2.4358845   0.015509894  0.10443088
654671 ge_npc    TCF20 ZSCAN2      4.0554205  -0.188057008 -0.17386339
654672 ge_npc    TCF20 ZSCAN21     2.3196547   0.042802411  0.09944789
654673 ge_npc    TCF20 ZSCAN22     0.5219204  -0.024538416 -0.02237569
654674 ge_npc    TCF20 ZSCAN23     3.2014590  -0.040828386 -0.13725248
654675 ge_npc    TCF20 ZSCAN25     1.0436975   0.063911357  0.04474525
654676 ge_npc    TCF20 ZSCAN29     2.8070725   0.133382719  0.12034440
654677 ge_npc    TCF20 ZSCAN31     2.6196196  -0.080119473 -0.11230795
654678 ge_npc    TCF20 ZSCAN5A     4.8866369  -0.059856542 -0.20949918
654679 ge_npc    TCF20 ZSCAN9      1.4546239   0.058099909  0.06236242
654680 ge_npc    TCF20 ZSWIM3      3.6721634   0.109459409  0.15743245
654681 ge_npc    TCF20 ZSWIM4      1.7180469  -0.073422407 -0.07365586
654682 ge_npc    TCF20 ZSWIM5      2.8835071  -0.001772917 -0.12362129
654683 ge_npc    TCF20 ZSWIM6      1.1037347   0.096501836  0.04731915
654684 ge_npc    TCF20 ZSWIM8      2.7915921  -0.016565672 -0.11968073
654685 ge_npc    TCF20 ZSWIM9      5.3137857   0.161591337  0.22781184
654686 ge_npc    TCF20 ZUP1        3.5615225  -0.064492316 -0.15268907
654687 ge_npc    TCF20 ZWILCH      1.5779904  -0.050658900 -0.06765137
654688 ge_npc    TCF20 ZWINT       2.0363218  -0.049977106 -0.08730089
654689 ge_npc    TCF20 ZXDB        1.8227080   0.022426274  0.07814287
654690 ge_npc    TCF20 ZZEF1       2.1025788   0.048069761  0.09014145
       pval         padj      significant
1      2.213302e-04 1.0000000 FALSE
2      8.974871e-05 0.8552154 FALSE
3      1.772867e-01 1.0000000 FALSE
4      3.375112e-02 1.0000000 FALSE
5      2.013703e-01 1.0000000 FALSE
6      1.810482e-01 1.0000000 FALSE
7      5.425328e-03 1.0000000 FALSE
8      1.565240e-02 1.0000000 FALSE
9      1.669932e-01 1.0000000 FALSE
10     4.126858e-03 1.0000000 FALSE
11     1.327609e-01 1.0000000 FALSE
12     4.530146e-02 1.0000000 FALSE
13     2.384865e-01 1.0000000 FALSE
14     5.901610e-02 1.0000000 FALSE
15     6.705692e-02 1.0000000 FALSE
16     1.782347e-01 1.0000000 FALSE
17     2.387531e-02 1.0000000 FALSE
18     1.802589e-01 1.0000000 FALSE
19     1.187443e-01 1.0000000 FALSE
20     2.572632e-04 1.0000000 FALSE
21     3.231534e-01 1.0000000 FALSE
22     7.530732e-04 1.0000000 FALSE
23     1.443676e-01 1.0000000 FALSE
24     2.451273e-02 1.0000000 FALSE
25     5.697267e-02 1.0000000 FALSE
26     8.962032e-02 1.0000000 FALSE
27     1.147186e-01 1.0000000 FALSE
28     2.650646e-01 1.0000000 FALSE
29     1.002958e-01 1.0000000 FALSE
30     1.138472e-01 1.0000000 FALSE
⋮      ⋮            ⋮         ⋮
654661 2.917836e-01 1.0000000 FALSE
654662 5.298207e-05 0.5100054 FALSE
654663 2.352689e-02 1.0000000 FALSE
654664 1.526619e-01 1.0000000 FALSE
654665 4.153830e-02 1.0000000 FALSE
654666 9.445369e-02 1.0000000 FALSE
654667 4.541251e-05 0.4380037 FALSE
654668 1.615407e-01 1.0000000 FALSE
654669 2.845209e-02 1.0000000 FALSE
654670 3.910202e-02 1.0000000 FALSE
654671 1.683031e-03 1.0000000 FALSE
654672 4.675500e-02 1.0000000 FALSE
654673 3.529527e-01 1.0000000 FALSE
654674 1.031381e-02 1.0000000 FALSE
654675 2.252390e-01 1.0000000 FALSE
654676 2.119958e-02 1.0000000 FALSE
654677 2.910932e-02 1.0000000 FALSE
654678 2.053151e-04 1.0000000 FALSE
654679 1.464622e-01 1.0000000 FALSE
654680 3.964687e-03 1.0000000 FALSE
654681 1.070834e-01 1.0000000 FALSE
654682 1.854169e-02 1.0000000 FALSE
654683 2.124275e-01 1.0000000 FALSE
654684 2.177542e-02 1.0000000 FALSE
654685 6.101921e-05 0.5868828 FALSE
654686 5.011042e-03 1.0000000 FALSE
654687 1.269506e-01 1.0000000 FALSE
654688 7.046864e-02 1.0000000 FALSE
654689 9.377498e-02 1.0000000 FALSE
654690 6.422847e-02 1.0000000 FALSE

In [10]:
sc.data <- fread_with_rownames(sc.data.file)
sc.metadata <- fread_with_rownames(sc.metadata.file)

Warning message in fread(file):
“Detected 75 column names but the data has 76 columns (i.e. invalid file). Added an extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.”

In [11]:
sc.metadata

                     orig.ident nCount_RNA nFeature_RNA percent.mito
AAACCCAGTTCATCGA-1_1 137116      6954      3747         0.043284441
AAACGCTTCAGTCACA-1_1 137116     33398      6683         0.013054674
AAAGAACCACTACGGC-1_1 137116      4380      2221         0.014383562
AAAGAACTCGAGTGGA-1_1 137116      7696      3195         0.051325364
AAAGGGCTCTCCTGCA-1_1 137116      5630      2517         0.026110124
AAAGTCCCAATTGTGC-1_1 137116      5442      2521         0.045938993
AAAGTGACAAATACAG-1_1 137116      9890      4028         0.016683519
AACAAAGGTCGGAAAC-1_1 137116      9729      3767         0.025285230
AACAACCTCCATCTCG-1_1 137116     26965      5625         0.014092342
AACACACGTTGAGAGC-1_1 137116      5319      2542         0.021056590
AACAGGGAGGGCAACT-1_1 137116     31021      7110         0.020276587
AACAGGGAGTACCATC-1_1 137116      8123      3020         0.027945340
AACCAACTCGTTACCC-1_1 137116      4104      2026         0.028021442
AACCACACATTCTTCA-1_1 137116     20603      5303         0.018104160
AACCATGTCGCTCCTA-1_1 137116      9693      3507         0.029093160
AACCCAATCATAGAGA-1_1 137116     10640      4668         0.025469925
AACCTGAGTGTAGTGG-1_1 137116     12441      4528         0.026444820
AACCTTTGTTGTTGAC-1_1 137116     20263      5136         0.006119528
AACGAAAAGCCTTGAT-1_1 137116      3713      1893         0.040398600
AACGAAAGTAGCGAGT-1_1 137116      4375      2341         0.014400000
AACGAAAGTGAGTAAT-1_1 137116      3203      1758         0.019981268
AACGGGAGTAAGTAGT-1_1 137116     10100      3812         0.020594059
AACTTCTGTTGGTGTT-1_1 137116     14751      4328         0.023184869
AACTTCTTCGATTGGT-1_1 137116      5420      2491         0.025276753
AAGAACAGTGTCTTAG-1_1 137116      6983      3237         0.005584992
AAGAACATCCACAGGC-1_1 137116      9898      3445         0.008385532
AAGACTCCACCTGTCT-1_1 137116     19097      5280         0.019060585
AAGACTCGTTCTTAGG-1_1 137116      6457      3036         0.048319653
AAGACTCTCGTTTACT-1_1 137116      3517      2066         0.052317316
AAGCCATAGCGTCAAG-1_1 137116      5487      2897         0.037178786
⋮                    ⋮          ⋮          ⋮            ⋮
TAACCAGGTGCATTTG-1_8 137123     11011      3710         0.049768413
TAACTTCCAACTCGAT-1_8 137123     44218      7567         0.028517798
TAGACTGGTGCAGGAT-1_8 137123     11392      4148         0.039238062
TAGTGCACAGGTTTAC-1_8 137123     14002      4478         0.031852592
TATCTGTTCGCTTGCT-1_8 137123     18365      5169         0.098012524
TCAAGACCATCATTGG-1_8 137123     18776      5052         0.015924585
TCAAGCAAGTCTCCTC-1_8 137123     33937      7126         0.031558476
TCAAGCACACTCAGAT-1_8 137123      9069      3513         0.015326938
TCAAGTGCAATTGCTG-1_8 137123     14630      4366         0.052084757
TCACAAGAGACTTGTC-1_8 137123      7929      3286         0.039853702
TCAGCAAGTAGAAACT-1_8 137123      4683      2094         0.053384583
TCAGCAATCCCTTTGG-1_8 137123     14532      4594         0.090283512
TCAGGTAAGCGGGTTA-1_8 137123      8843      3274         0.037543820
TCATCCGTCCGTGACG-1_8 137123     14833      4756         0.063978966
TCCCACAAGGTACTGG-1_8 137123     47956      7629         0.034198015
TCGACCTAGCATTGAA-1_8 137123      9904      3475         0.019588045
TCGCTTGAGCCTGTGC-1_8 137123      5070      2518         0.035305720
TCTTTGACAGGTTCGC-1_8 137123     15658      4451         0.003768042
TGACCCTTCCATACTT-1_8 137123     25859      6734         0.025600371
TGGAGAGTCCCTCTTT-1_8 137123     18737      5553         0.046272082
TGGGCTGTCCCGAACG-1_8 137123     25982      6067         0.083596336
TGGTTAGAGCTTTGTG-1_8 137123      9971      3856         0.041119246
TGTTCATGTGGGCTCT-1_8 137123     10860      4087         0.033149171
TTAATCCAGCGCCTAC-1_8 137123      8051      3309         0.006955658
TTACGTTGTGCCTGAC-1_8 137123     16982      5362         0.029030738
TTCCAATAGATCACTC-1_8 137123      6808      2840         0.031286722
TTCTTCCAGGTTCACT-1_8 137123     12106      4479         0.001156451
TTCTTCCCATTGACTG-1_8 137123     17722      5386         0.013316781
TTTCAGTTCCCGTGTT-1_8 137123     24210      6078         0.030855019
TTTGGAGAGCATAGGC-1_8 137123      3608      2052         0.014135255
                     percent.ribo percent.AC.GenBank percent.AL.EMBL
AAACCCAGTTCATCGA-1_1 0.01121657   0.02300834         0.010928962
AAACGCTTCAGTCACA-1_1 0.01949219   0.01982155         0.006018324
AAAGAACCACTACGGC-1_1 0.05639269   0.01803653         0.003881279
AAAGAACTCGAGTGGA-1_1 0.06535863   0.01234407         0.004937630
AAAGGGCTCTCCTGCA-1_1 0.06429840   0.02113677         0.003374778
AAAGTCCCAATTGTGC-1_1 0.05071665   0.01764057         0.011944138
AAAGTGACAAATACAG-1_1 0.01375126   0.01577351         0.008190091
AACAAAGGTCGGAAAC-1_1 0.04779525   0.01274540         0.004008634
AACAACCTCCATCTCG-1_1 0.02058224   0.01594660         0.004116447
AACACACGTTGAGAGC-1_1 0.03778906   0.01748449         0.006580184
AACAGGGAGGGCAACT-1_1 0.02981851   0.01489314         0.003803875
AACAGGGAGTACCATC-1_1 0.03779392   0.01403422         0.002092823
AACCAACTCGTTACCC-1_1 0.02753411   0.02046784         0.006091618
AACCACACATTCTTCA-1_1 0.02213270   0.01655099         0.004902199
AACCATGTCGCTCCTA-1_1 0.10368307   0.01361807         0.006912205
AACCCAATCATAGAGA-1_1 0.03092105   0.01851504         0.009586466
AACCTGAGTGTAGTGG-1_1 0.02250623   0.01470943         0.003617073
AACCTTTGTTGTTGAC-1_1 0.03627301   0.01559493         0.013916992
AACGAAAAGCCTTGAT-1_1 0.10045785   0.01804471         0.005117156
AACGAAAGTAGCGAGT-1_1 0.05120000   0.01622857         0.008000000
AACGAAAGTGAGTAAT-1_1 0.08211052   0.01436154         0.006244146
AACGGGAGTAAGTAGT-1_1 0.04277228   0.01643564         0.005049505
AACTTCTGTTGGTGTT-1_1 0.02359162   0.01118568         0.010033218
AACTTCTTCGATTGGT-1_1 0.03339483   0.01697417         0.004797048
AAGAACAGTGTCTTAG-1_1 0.06200773   0.02549048         0.008735501
AAGAACATCCACAGGC-1_1 0.03182461   0.01808446         0.009698929
AAGACTCCACCTGTCT-1_1 0.03728334   0.02157407         0.004032047
AAGACTCGTTCTTAGG-1_1 0.02137215   0.01254453         0.006349698
AAGACTCTCGTTTACT-1_1 0.09354564   0.01307933         0.003980665
AAGCCATAGCGTCAAG-1_1 0.03098232   0.01749590         0.005467469
⋮                    ⋮            ⋮                  ⋮
TAACCAGGTGCATTTG-1_8 0.08618654   0.010716556        0.005085823
TAACTTCCAACTCGAT-1_8 0.04387354   0.019245556        0.003686282
TAGACTGGTGCAGGAT-1_8 0.05451194   0.011235955        0.008778090
TAGTGCACAGGTTTAC-1_8 0.03892301   0.012569633        0.005356378
TATCTGTTCGCTTGCT-1_8 0.09022597   0.013776205        0.004029404
TCAAGACCATCATTGG-1_8 0.02657648   0.015764806        0.003887942
TCAAGCAAGTCTCCTC-1_8 0.07242832   0.018328078        0.003241300
TCAAGCACACTCAGAT-1_8 0.02613298   0.013231889        0.006726210
TCAAGTGCAATTGCTG-1_8 0.04155844   0.017224880        0.006561859
TCACAAGAGACTTGTC-1_8 0.03443057   0.011602976        0.005423130
TCAGCAAGTAGAAACT-1_8 0.09139441   0.010890455        0.002348922
TCAGCAATCCCTTTGG-1_8 0.07053399   0.005229838        0.002064410
TCAGGTAAGCGGGTTA-1_8 0.10709035   0.011534547        0.002714011
TCATCCGTCCGTGACG-1_8 0.07523765   0.012337356        0.007011394
TCCCACAAGGTACTGG-1_8 0.03978647   0.019288514        0.004587539
TCGACCTAGCATTGAA-1_8 0.07471729   0.016457997        0.003634895
TCGCTTGAGCCTGTGC-1_8 0.07672584   0.016173570        0.004536489
TCTTTGACAGGTTCGC-1_8 0.01149572   0.022352791        0.011687316
TGACCCTTCCATACTT-1_8 0.01403767   0.014037666        0.007772922
TGGAGAGTCCCTCTTT-1_8 0.08293750   0.013395955        0.004056146
TGGGCTGTCCCGAACG-1_8 0.10341775   0.012547148        0.003348472
TGGTTAGAGCTTTGTG-1_8 0.04783873   0.013238391        0.006117741
TGTTCATGTGGGCTCT-1_8 0.07550645   0.011233886        0.003130755
TTAATCCAGCGCCTAC-1_8 0.07464911   0.014532356        0.005961992
TTACGTTGTGCCTGAC-1_8 0.05293841   0.011364975        0.004180897
TTCCAATAGATCACTC-1_8 0.09885429   0.014247944        0.004847239
TTCTTCCAGGTTCACT-1_8 0.05088386   0.014207831        0.004873616
TTCTTCCCATTGACTG-1_8 0.02623857   0.017548809        0.008012640
TTTCAGTTCCCGTGTT-1_8 0.05130112   0.016232962        0.003097893
TTTGGAGAGCATAGGC-1_8 0.03131929   0.020232816        0.003325942
                     percent.LINC percent.MALAT1 percent.antisense ⋯
AAACCCAGTTCATCGA-1_1 0.008196721  0.009059534    0.009922347       ⋯
AAACGCTTCAGTCACA-1_1 0.008383736  0.027426792    0.011228217       ⋯
AAAGAACCACTACGGC-1_1 0.005707763  0.110730594    0.013926941       ⋯
AAAGAACTCGAGTGGA-1_1 0.004028067  0.008316008    0.005587318       ⋯
AAAGGGCTCTCCTGCA-1_1 0.003019538  0.074955595    0.009946714       ⋯
AAAGTCCCAATTGTGC-1_1 0.005696435  0.064865858    0.005512679       ⋯
AAAGTGACAAATACAG-1_1 0.009908999  0.133569262    0.011223458       ⋯
AACAAAGGTCGGAAAC-1_1 0.006167129  0.025285230    0.009353479       ⋯
AACAACCTCCATCTCG-1_1 0.008566660  0.045837196    0.006786575       ⋯
AACACACGTTGAGAGC-1_1 0.004888137  0.067493890    0.011280316       ⋯
AACAGGGAGGGCAACT-1_1 0.008059057  0.019921988    0.007188679       ⋯
AACAGGGAGTACCATC-1_1 0.007878862  0.060199434    0.015634618       ⋯
AACCAACTCGTTACCC-1_1 0.007066277  0.091374269    0.009259259       ⋯
AACCACACATTCTTCA-1_1 0.007377566  0.045527350    0.010775130       ⋯
AACCATGTCGCTCCTA-1_1 0.005777365  0.044980914    0.008253379       ⋯
AACCCAATCATAGAGA-1_1 0.006672932  0.010808271    0.009962406       ⋯
AACCTGAGTGTAGTGG-1_1 0.005063902  0.021380918    0.006430351       ⋯
AACCTTTGTTGTTGAC-1_1 0.015446874  0.066475843    0.005774071       ⋯
AACGAAAAGCCTTGAT-1_1 0.003501212  0.070024239    0.009157016       ⋯
AACGAAAGTAGCGAGT-1_1 0.005028571  0.004800000    0.015542857       ⋯
AACGAAAGTGAGTAAT-1_1 0.004370902  0.076178583    0.010927256       ⋯
AACGGGAGTAAGTAGT-1_1 0.004257426  0.023564356    0.010990099       ⋯
AACTTCTGTTGGTGTT-1_1 0.006033489  0.098772965    0.007321538       ⋯
AACTTCTTCGATTGGT-1_1 0.003505535  0.013653137    0.009963100       ⋯
AAGAACAGTGTCTTAG-1_1 0.006157812  0.070743234    0.011456394       ⋯
AAGAACATCCACAGGC-1_1 0.003738129  0.070519297    0.007577288       ⋯
AAGACTCCACCTGTCT-1_1 0.007383359  0.046394722    0.007226266       ⋯
AAGACTCGTTCTTAGG-1_1 0.006504569  0.050487843    0.010221465       ⋯
AAGACTCTCGTTTACT-1_1 0.005117998  0.029001990    0.008814330       ⋯
AAGCCATAGCGTCAAG-1_1 0.005285220  0.024421360    0.007107709       ⋯
⋮                    ⋮            ⋮              ⋮                 ⋱
TAACCAGGTGCATTTG-1_8 0.004268459  0.0750158932   0.004177641       ⋯
TAACTTCCAACTCGAT-1_8 0.005178886  0.0389208015   0.006581030       ⋯
TAGACTGGTGCAGGAT-1_8 0.006495787  0.0530196629   0.005881320       ⋯
TAGTGCACAGGTTTAC-1_8 0.005856306  0.0629195829   0.008284531       ⋯
TATCTGTTCGCTTGCT-1_8 0.004465015  0.0505309012   0.005445140       ⋯
TCAAGACCATCATTGG-1_8 0.008148700  0.0539518534   0.009959523       ⋯
TCAAGCAAGTCTCCTC-1_8 0.004390488  0.0293190323   0.006659398       ⋯
TCAAGCACACTCAGAT-1_8 0.005292756  0.1260337413   0.008269931       ⋯
TCAAGTGCAATTGCTG-1_8 0.006356801  0.0779904306   0.011141490       ⋯
TCACAAGAGACTTGTC-1_8 0.005170892  0.0624290579   0.005549250       ⋯
TCAGCAAGTAGAAACT-1_8 0.004697843  0.0965193252   0.012171685       ⋯
TCAGCAATCCCTTTGG-1_8 0.001720341  0.0007569502   0.003647124       ⋯
TCAGGTAAGCGGGTTA-1_8 0.004862603  0.0045233518   0.007689698       ⋯
TCATCCGTCCGTGACG-1_8 0.006943976  0.0372143194   0.008157487       ⋯
TCCCACAAGGTACTGG-1_8 0.005129702  0.0341354575   0.007465176       ⋯
TCGACCTAGCATTGAA-1_8 0.008178514  0.0724959612   0.010197900       ⋯
TCGCTTGAGCCTGTGC-1_8 0.005917160  0.0544378698   0.009861933       ⋯
TCTTTGACAGGTTCGC-1_8 0.009962958  0.0819389449   0.009643633       ⋯
TGACCCTTCCATACTT-1_8 0.006806141  0.1107544762   0.007888936       ⋯
TGGAGAGTCCCTCTTT-1_8 0.004963441  0.0139296579   0.006884773       ⋯
TGGGCTGTCCCGAACG-1_8 0.004811023  0.0147794627   0.006542991       ⋯
TGGTTAGAGCTTTGTG-1_8 0.006619196  0.0732123157   0.006719487       ⋯
TGTTCATGTGGGCTCT-1_8 0.006261510  0.0321362799   0.005156538       ⋯
TTAATCCAGCGCCTAC-1_8 0.004844119  0.0919140479   0.006458825       ⋯
TTACGTTGTGCCTGAC-1_8 0.006006360  0.0425156048   0.005947474       ⋯
TTCCAATAGATCACTC-1_8 0.005141011  0.0847532315   0.010135135       ⋯
TTCTTCCAGGTTCACT-1_8 0.006856104  0.0193292582   0.008260367       ⋯
TTCTTCCCATTGACTG-1_8 0.006206974  0.0533799797   0.009874732       ⋯
TTTCAGTTCCCGTGTT-1_8 0.006650145  0.0140437836   0.008137133       ⋯
TTTGGAGAGCATAGGC-1_8 0.006097561  0.0554323725   0.008037694       ⋯
                     celltype_jf_ctrl RNA_snn_res.10 celltype_ctrl_transfer
AAACCCAGTTCATCGA-1_1 NA                90            L6_CThPN
AAACGCTTCAGTCACA-1_1 NA                85            L56
AAAGAACCACTACGGC-1_1 NA                 3            CGE_IN
AAAGAACTCGAGTGGA-1_1 NA                34            L23
AAAGGGCTCTCCTGCA-1_1 NA                39            CGE_LGE_IN
AAAGTCCCAATTGTGC-1_1 NA                48            IP
AAAGTGACAAATACAG-1_1 NA                49            oRG
AACAAAGGTCGGAAAC-1_1 NA                11            ccvRG
AACAACCTCCATCTCG-1_1 NA                11            ccvRG
AACACACGTTGAGAGC-1_1 NA                23            CGE_IN
AACAGGGAGGGCAACT-1_1 NA                92            ccvRG
AACAGGGAGTACCATC-1_1 NA                16            CGE_IN
AACCAACTCGTTACCC-1_1 NA                 5            CGE_IN
AACCACACATTCTTCA-1_1 NA                11            ccvRG
AACCATGTCGCTCCTA-1_1 NA                14            oRG
AACCCAATCATAGAGA-1_1 NA                81            L23
AACCTGAGTGTAGTGG-1_1 NA                77            ccvRG
AACCTTTGTTGTTGAC-1_1 NA                55            L56
AACGAAAAGCCTTGAT-1_1 NA                89            LGE_IN
AACGAAAGTAGCGAGT-1_1 NA                 3            CGE_IN
AACGAAAGTGAGTAAT-1_1 NA                23            CGE_IN
AACGGGAGTAAGTAGT-1_1 NA                70            ccvRG
AACTTCTGTTGGTGTT-1_1 NA                55            L56
AACTTCTTCGATTGGT-1_1 NA                20            INP
AAGAACAGTGTCTTAG-1_1 NA                65            L6_CThPN
AAGAACATCCACAGGC-1_1 NA                55            L6_CThPN
AAGACTCCACCTGTCT-1_1 NA                73            ccvRG
AAGACTCGTTCTTAGG-1_1 NA                12            L23
AAGACTCTCGTTTACT-1_1 NA               103            INP
AAGCCATAGCGTCAAG-1_1 NA                61            L56
⋮                    ⋮                ⋮              ⋮
TAACCAGGTGCATTTG-1_8 IP                78            IP
TAACTTCCAACTCGAT-1_8 ccvRG              9            ccvRG
TAGACTGGTGCAGGAT-1_8 IP                19            IP
TAGTGCACAGGTTTAC-1_8 L56               42            L56
TATCTGTTCGCTTGCT-1_8 OPC               13            OPC
TCAAGACCATCATTGG-1_8 CGE_LGE_IN        39            CGE_LGE_IN
TCAAGCAAGTCTCCTC-1_8 vRG               22            vRG
TCAAGCACACTCAGAT-1_8 L56                2            L56
TCAAGTGCAATTGCTG-1_8 IP                24            L56
TCACAAGAGACTTGTC-1_8 L56               42            L56
TCAGCAAGTAGAAACT-1_8 LGE_IN            98            LGE_IN
TCAGCAATCCCTTTGG-1_8 ccvRG             29            ccvRG
TCAGGTAAGCGGGTTA-1_8 vRG               35            INP
TCATCCGTCCGTGACG-1_8 oRG               45            oRG
TCCCACAAGGTACTGG-1_8 ccvRG             73            ccvRG
TCGACCTAGCATTGAA-1_8 INP               15            INP
TCGCTTGAGCCTGTGC-1_8 CGE_LGE_IN        39            CGE_LGE_IN
TCTTTGACAGGTTCGC-1_8 IP                32            IP
TGACCCTTCCATACTT-1_8 oRG               49            oRG
TGGAGAGTCCCTCTTT-1_8 vRG               22            vRG
TGGGCTGTCCCGAACG-1_8 OPC               13            OPC
TGGTTAGAGCTTTGTG-1_8 IP                19            IP
TGTTCATGTGGGCTCT-1_8 vRG              121            INP
TTAATCCAGCGCCTAC-1_8 L56               62            L23
TTACGTTGTGCCTGAC-1_8 ccRG              97            ccvRG
TTCCAATAGATCACTC-1_8 CGE_IN            37            CGE_IN
TTCTTCCAGGTTCACT-1_8 RG                14            RG
TTCTTCCCATTGACTG-1_8 vRG               22            vRG
TTTCAGTTCCCGTGTT-1_8 ccvRG             88            ccvRG
TTTGGAGAGCATAGGC-1_8 LGE_IN            21            LGE_IN
                     this  celltype_ctrl_transfer_score SEQID_GEX batch2_pool
AAACCCAGTTCATCGA-1_1 FALSE 1.0000000                    NA        NA
AAACGCTTCAGTCACA-1_1 FALSE 0.5842084                    NA        NA
AAAGAACCACTACGGC-1_1 FALSE 0.8609243                    NA        NA
AAAGAACTCGAGTGGA-1_1 FALSE 1.0000000                    NA        NA
AAAGGGCTCTCCTGCA-1_1 FALSE 0.7754296                    NA        NA
AAAGTCCCAATTGTGC-1_1 FALSE 0.9610091                    NA        NA
AAAGTGACAAATACAG-1_1 FALSE 1.0000000                    NA        NA
AACAAAGGTCGGAAAC-1_1 FALSE 1.0000000                    NA        NA
AACAACCTCCATCTCG-1_1 FALSE 0.9678375                    NA        NA
AACACACGTTGAGAGC-1_1 FALSE 1.0000000                    NA        NA
AACAGGGAGGGCAACT-1_1 FALSE 1.0000000                    NA        NA
AACAGGGAGTACCATC-1_1 FALSE 0.8624593                    NA        NA
AACCAACTCGTTACCC-1_1 FALSE 1.0000000                    NA        NA
AACCACACATTCTTCA-1_1 FALSE 1.0000000                    NA        NA
AACCATGTCGCTCCTA-1_1 FALSE 0.4868951                    NA        NA
AACCCAATCATAGAGA-1_1 FALSE 1.0000000                    NA        NA
AACCTGAGTGTAGTGG-1_1 FALSE 1.0000000                    NA        NA
AACCTTTGTTGTTGAC-1_1 FALSE 0.6367836                    NA        NA
AACGAAAAGCCTTGAT-1_1 FALSE 0.6081094                    NA        NA
AACGAAAGTAGCGAGT-1_1 FALSE 0.9480474                    NA        NA
AACGAAAGTGAGTAAT-1_1 FALSE 1.0000000                    NA        NA
AACGGGAGTAAGTAGT-1_1 FALSE 1.0000000                    NA        NA
AACTTCTGTTGGTGTT-1_1 FALSE 0.6846889                    NA        NA
AACTTCTTCGATTGGT-1_1 FALSE 0.7626230                    NA        NA
AAGAACAGTGTCTTAG-1_1 FALSE 0.8080049                    NA        NA
AAGAACATCCACAGGC-1_1 FALSE 0.6060251                    NA        NA
AAGACTCCACCTGTCT-1_1 FALSE 1.0000000                    NA        NA
AAGACTCGTTCTTAGG-1_1 FALSE 1.0000000                    NA        NA
AAGACTCTCGTTTACT-1_1 FALSE 0.4400468                    NA        NA
AAGCCATAGCGTCAAG-1_1 FALSE 0.7713942                    NA        NA
⋮                    ⋮     ⋮                            ⋮         ⋮
TAACCAGGTGCATTTG-1_8 FALSE 1.0000000                    NA        NA
TAACTTCCAACTCGAT-1_8 FALSE 1.0000000                    NA        NA
TAGACTGGTGCAGGAT-1_8 FALSE 1.0000000                    NA        NA
TAGTGCACAGGTTTAC-1_8 FALSE 0.9947427                    NA        NA
TATCTGTTCGCTTGCT-1_8 FALSE 0.9033614                    NA        NA
TCAAGACCATCATTGG-1_8 FALSE 0.9291906                    NA        NA
TCAAGCAAGTCTCCTC-1_8 FALSE 0.6511089                    NA        NA
TCAAGCACACTCAGAT-1_8 FALSE 0.9914455                    NA        NA
TCAAGTGCAATTGCTG-1_8 FALSE 0.7125905                    NA        NA
TCACAAGAGACTTGTC-1_8 FALSE 0.9946661                    NA        NA
TCAGCAAGTAGAAACT-1_8 FALSE 0.7148128                    NA        NA
TCAGCAATCCCTTTGG-1_8 FALSE 0.9366063                    NA        NA
TCAGGTAAGCGGGTTA-1_8 FALSE 0.9116998                    NA        NA
TCATCCGTCCGTGACG-1_8 FALSE 1.0000000                    NA        NA
TCCCACAAGGTACTGG-1_8 FALSE 1.0000000                    NA        NA
TCGACCTAGCATTGAA-1_8 FALSE 0.9258033                    NA        NA
TCGCTTGAGCCTGTGC-1_8 FALSE 0.9815755                    NA        NA
TCTTTGACAGGTTCGC-1_8 FALSE 1.0000000                    NA        NA
TGACCCTTCCATACTT-1_8 FALSE 1.0000000                    NA        NA
TGGAGAGTCCCTCTTT-1_8 FALSE 0.9487508                    NA        NA
TGGGCTGTCCCGAACG-1_8 FALSE 0.9962889                    NA        NA
TGGTTAGAGCTTTGTG-1_8 FALSE 1.0000000                    NA        NA
TGTTCATGTGGGCTCT-1_8 FALSE 0.9719746                    NA        NA

In [12]:
sc.data

                                            AAACCCAGTTCATCGA-1_1
AL627309.1                                  0
LINC00115                                   0
NOC2L                                       0
KLHL17                                      0
AL645608.7                                  0
HES4                                        0
ISG15                                       0
AGRN                                        0
C1orf159                                    0
SDF4                                        0
B3GALT6                                     0
UBE2J2                                      0
SCNN1D                                      0
ACAP3                                       0
PUSL1                                       0
INTS11                                      0
CPTP                                        0
DVL1                                        0
MXRA8                                       0
AURKAIP1                                    0
CCNL2                                       0
MRPL20                                      0
VWA1                                        0
ATAD3B                                      0
ATAD3A                                      0
SSU72                                       0
AL645728.1                                  0
FNDC10                                      0
AL691432.2                                  0
MIB2                                        0
⋮                                           ⋮
L34079.1                                    0.0000000
AC067968.1                                  0.0000000
AC245748.1                                  0.0000000
AC243964.2                                  0.0000000
AC011452.1                                  0.0000000
AC010487.3                                  0.0000000
AC006115.1                                  0.0000000
AC006115.3                                  0.0000000
ZIM2-AS1                                    0.0000000
AC003002.2                                  0.9005354
AC004076.1                                  0.9005354
AC003006.1                                  0.0000000
AC010522.1                                  0.0000000
AC020915.3                                  0.0000000
AC007326.4                                  0.0000000
Z82190.2                                    0.0000000
Z83844.1                                    0.0000000
H1-0                                        0.0000000
TPTEP2-CSNK1E                               0.0000000
C22orf46                                    0.0000000
AL021453.1                                  0.0000000
PRR5-ARHGAP8                                0.0000000
FP671120.1                                  0.0000000
FP236383.1                                  0.0000000
AF127577.4                                  0.0000000
AP000254.1                                  0.0000000
AP000311.1                                  0.0000000
AC004556.1                                  0.0000000
After-flox.Flag.NLS.Cas9.dTom.WPRE.HAL.SV40 1.3665611
iCrop-Chong.Guides.and.BC.masked.FIX        0.0000000
                                            AAACGCTTCAGTCACA-1_1
AL627309.1                                  0.2629286
LINC00115                                   0.0000000
NOC2L                                       0.0000000
KLHL17                                      0.0000000
AL645608.7                                  0.0000000
HES4                                        0.0000000
ISG15                                       0.0000000
AGRN                                        0.0000000
C1orf159                                    0.4709204
SDF4                                        0.0000000
B3GALT6                                     0.0000000
UBE2J2                                      0.0000000
SCNN1D                                      0.0000000
ACAP3                                       0.0000000
PUSL1                                       0.0000000
INTS11                                      0.0000000
CPTP                                        0.0000000
DVL1                                        0.0000000
MXRA8                                       0.0000000
AURKAIP1                                    0.0000000
CCNL2                                       0.2629286
MRPL20                                      0.0000000
VWA1                                        0.0000000
ATAD3B                                      0.0000000
ATAD3A                                      0.0000000
SSU72                                       0.0000000
AL645728.1                                  0.0000000
FNDC10                                      0.0000000
AL691432.2                                  0.0000000
MIB2                                        0.0000000
⋮                                           ⋮
L34079.1                                    0.0000000
AC067968.1                                  0.0000000
AC245748.1                                  0.0000000
AC243964.2                                  0.0000000
AC011452.1                                  0.0000000
AC010487.3                                  0.0000000
AC006115.1                                  0.0000000
AC006115.3                                  0.0000000
ZIM2-AS1                                    0.0000000
AC003002.2                                  0.0000000
AC004076.1                                  0.7897906
AC003006.1                                  0.0000000
AC010522.1                                  0.0000000
AC020915.3                                  0.0000000
AC007326.4                                  0.2629286
Z82190.2                                    0.0000000
Z83844.1                                    0.0000000
H1-0                                        0.2629286
TPTEP2-CSNK1E                               1.2255005
C22orf46                                    0.0000000
AL021453.1                                  0.0000000
PRR5-ARHGAP8                                0.0000000
FP671120.1                                  0.2629286
FP236383.1                                  0.0000000
AF127577.4                                  0.0000000
AP000254.1                                  0.0000000
AP000311.1                                  0.9177572
AC004556.1                                  0.0000000
After-flox.Flag.NLS.Cas9.dTom.WPRE.HAL.SV40 0.6430118
iCrop-Chong.Guides.and.BC.masked.FIX        0.0000000
                                            AAAGAACCACTACGGC-1_1
AL627309.1                                  0.000000
LINC00115                                   0.000000
NOC2L                                       0.000000
KLHL17                                      0.000000
AL645608.7                                  0.000000
HES4                                        0.000000
ISG15                                       0.000000
AGRN                                        0.000000
C1orf159                                    0.000000
SDF4                                        0.000000
B3GALT6                                     0.000000
UBE2J2                                      0.000000
SCNN1D                                      0.000000
ACAP3                                       0.000000
PUSL1                                       0.000000
INTS11                                      0.000000
CPTP                                        0.000000
DVL1                                        0.000000
MXRA8                                       0.000000
AURKAIP1                                    0.000000
CCNL2                                       1.191336
MRPL20                                      0.000000
VWA1                                        0.000000
ATAD3B                                      0.000000
ATAD3A                                      0.000000
SSU72                                       0.000000
AL645728.1                                  0.000000
FNDC10                                      0.000000
AL691432.2                                  0.000000
MIB2                                        0.000000
⋮                                           ⋮
L34079.1                                    0.000000
AC067968.1                                  0.000000
AC245748.1                                  0.000000
AC243964.2                                  0.000000
AC011452.1                                  0.000000
AC010487.3                                  0.000000
AC006115.1                                  0.000000
AC006115.3                                  0.000000
ZIM2-AS1                                    0.000000
AC003002.2                                  1.191336
AC004076.1                                  1.191336
AC003006.1                                  0.000000
AC010522.1                                  0.000000
AC020915.3                                  0.000000
AC007326.4                                  0.000000
Z82190.2                                    0.000000
Z83844.1                                    0.000000
H1-0                                        0.000000
TPTEP2-CSNK1E                               0.000000
C22orf46                                    0.000000
AL021453.1                                  0.000000
PRR5-ARHGAP8                                0.000000
FP671120.1                                  0.000000
FP236383.1                                  0.000000
AF127577.4                                  0.000000
AP000254.1                                  0.000000
AP000311.1                                  0.000000
AC004556.1                                  0.000000
After-flox.Flag.NLS.Cas9.dTom.WPRE.HAL.SV40 1.191336
iCrop-Chong.Guides.and.BC.masked.FIX        0.000000
                                            AAAGAACTCGAGTGGA-1_1
AL627309.1                                  0.0000000
LINC00115                                   0.0000000
NOC2L                                       0.8345517
KLHL17                                      0.0000000
AL645608.7                                  0.0000000
HES4                                        0.0000000
ISG15                                       0.0000000
AGRN                                        0.0000000
C1orf159                                    0.0000000
SDF4                                        0.0000000
B3GALT6                                     0.0000000
UBE2J2                                      0.0000000
SCNN1D                                      0.0000000
ACAP3                                       0.0000000
PUSL1                                       0.0000000
INTS11                                      0.0000000
CPTP                                        0.0000000
DVL1                                        0.0000000
MXRA8                                       0.0000000
AURKAIP1                                    0.0000000
CCNL2                                       0.0000000
MRPL20                                      0.8345517
VWA1                                        0.0000000
ATAD3B                                      0.0000000
ATAD3A                                      0.0000000
SSU72                                       0.8345517
AL645728.1                                  0.0000000
FNDC10                                      0.0000000
AL691432.2                                  0.0000000
MIB2                                        0.0000000
⋮                                           ⋮
L34079.1                                    0.0000000
AC067968.1                                  0.0000000
AC245748.1                                  0.0000000
AC243964.2                                  0.0000000
AC011452.1                                  0.0000000
AC010487.3                                  0.0000000
AC006115.1                                  0.0000000
AC006115.3                                  0.0000000
ZIM2-AS1                                    0.0000000
AC003002.2                                  0.0000000
AC004076.1                                  0.0000000
AC003006.1                                  0.0000000
AC010522.1                                  0.0000000
AC020915.3                                  0.0000000
AC007326.4                                  0.0000000
Z82190.2                                    0.0000000
Z83844.1                                    0.0000000
H1-0                                        0.0000000
TPTEP2-CSNK1E                               0.0000000
C22orf46                                    0.0000000
AL021453.1                                  0.0000000
PRR5-ARHGAP8                                0.0000000
FP671120.1                                  0.8345517
FP236383.1                                  0.0000000
AF127577.4                                  0.0000000
AP000254.1                                  0.0000000
AP000311.1                                  0.0000000
AC004556.1                                  0.0000000
After-flox.Flag.NLS.Cas9.dTom.WPRE.HAL.SV40 0.0000000
iCrop-Chong.Guides.and.BC.masked.FIX        1.2830322
                                            AAAGGGCTCTCCTGCA-1_1
AL627309.1                                  0.000000
LINC00115                                   1.023704
NOC2L                                       0.000000
KLHL17                                      0.000000
AL645608.7                                  0.000000
HES4                                        0.000000
ISG15                                       0.000000
AGRN                                        0.000000
C1orf159                                    1.023704
SDF4                                        1.023704
B3GALT6                                     0.000000
UBE2J2                                      0.000000
SCNN1D                                      0.000000
ACAP3                                       1.023704
PUSL1                                       0.000000
INTS11                                      0.000000
CPTP                                        0.000000
DVL1                                        0.000000
MXRA8                                       0.000000
AURKAIP1                                    0.000000
CCNL2                                       0.000000
MRPL20                                      0.000000
VWA1                                        0.000000
ATAD3B                                      0.000000
ATAD3A                                      0.000000
SSU72                                       0.000000
AL645728.1                                  0.000000
FNDC10                                      0.000000
AL691432.2                                  0.000000
MIB2                                        0.000000
⋮                                           ⋮
L34079.1                                    0.000000
AC067968.1                                  0.000000
AC245748.1                                  0.000000
AC243964.2                                  0.000000
AC011452.1                                  0.000000
AC010487.3                                  0.000000
AC006115.1                                  0.000000
AC006115.3                                  0.000000
ZIM2-AS1                                    0.000000
AC003002.2                                  0.000000
AC004076.1                                  0.000000
AC003006.1                                  0.000000
AC010522.1                                  0.000000
AC020915.3                                  1.023704
AC007326.4                                  0.000000
Z82190.2                                    0.000000
Z83844.1                                    0.000000
H1-0                                        1.023704
TPTEP2-CSNK1E                               1.848526
C22orf46                                    0.000000
AL021453.1                                  0.000000
PRR5-ARHGAP8                                0.000000
FP671120.1                                  1.023704
FP236383.1                                  0.000000
AF127577.4                                  0.000000
AP000254.1                                  0.000000
AP000311.1                                  1.023704
AC004556.1                                  0.000000
After-flox.Flag.NLS.Cas9.dTom.WPRE.HAL.SV40 1.518850
iCrop-Chong.Guides.and.BC.masked.FIX        0.000000
                                            AAAGTCCCAATTGTGC-1_1
AL627309.1                                  0.00000
LINC00115                                   0.00000
NOC2L                                       0.00000
KLHL17                                      0.00000
AL645608.7                                  0.00000
HES4                                        0.00000
ISG15                                       0.00000
AGRN                                        0.00000
C1orf159                                    0.00000
SDF4                                        0.00000
B3GALT6                                     0.00000
UBE2J2                                      0.00000
SCNN1D                                      0.00000
ACAP3                                       0.00000
PUSL1                                       0.00000
INTS11                                      0.00000
CPTP                                        0.00000
DVL1                                        1.04557
MXRA8                                       0.00000
AURKAIP1                                    0.00000
CCNL2                                       1.04557
MRPL20                                      1.54544
VWA1                                        0.00000
ATAD3B                                      0.00000
ATAD3A                                      0.00000
SSU72                                       0.00000
AL645728.1                                  0.00000
FNDC10                                      0.00000
AL691432.2                                  0.00000
MIB2                                        0.00000
⋮                                           ⋮
L34079.1                                    0.000000
AC067968.1                                  0.000000
AC245748.1                                  0.000000
AC243964.2                                  0.000000
AC011452.1                                  0.000000
AC010487.3                                  0.000000
AC006115.1                                  0.000000
AC006115.3                                  0.000000
ZIM2-AS1                                    0.000000
AC003002.2                                  0.000000
AC004076.1                                  0.000000
AC003006.1                                  0.000000
AC010522.1                                  0.000000
AC020915.3                                  0.000000
AC007326.4                                  0.000000
Z82190.2                                    0.000000
Z83844.1                                    0.000000
H1-0                                        0.000000
TPTEP2-CSNK1E                               1.545440
C22orf46                                    0.000000
AL021453.1                                  0.000000
PRR5-ARHGAP8                                0.000000
FP671120.1                                  0.000000
FP236383.1                                  0.000000
AF127577.4                                  0.000000
AP000254.1                                  0.000000
AP000311.1                                  0.000000
AC004556.1                                  0.000000
After-flox.Flag.NLS.Cas9.dTom.WPRE.HAL.SV40 0.000000
iCrop-Chong.Guides.and.BC.masked.FIX        2.125857
                                            AAAGTGACAAATACAG-1_1
AL627309.1                                  0.000000
LINC00115                                   0.000000
NOC2L                                       0.701757
KLHL17                                      0.000000
AL645608.7                                  0.000000

In [13]:
# Read in the TF / cell type combinations to analyze
tfs.to.analyze <- read.csv(tfs.to.analyze.file, header=TRUE)

In [14]:
tfs.to.analyze

  TF     celltype_jf median.expression.multiome median.expression.scrnaseq
1 MYT1L  ge_in       1.559380                   1.602277
2 BCL11A ctx_npc     1.317189                   1.299130
3 KDM5B  ge_in       1.688875                   1.598961
4 KMT2A  ctx_npc     1.266685                   1.213317
5 ASH1L  ge_in       1.457661                   1.493587
6 ASH1L  ctx_ip      1.304190                   1.299186
  wt.expr.gt.ko.pval reported.efficiency.of.sgrna
1 0.001133629        strong
2 0.005426838        strong
3 0.034082582        strong
4 0.039354873        strong
5 0.042533059        strong
6 0.092750568        strong

In [15]:
score.viper <- function(predictions.tbl, sc.metadata, sc.data,
                        sc.cell.type.col = "celltype_jf", sc.genotype.col = "gRNA_perturb", sc.wt.status = "CTRL")
{
  #' Apply VIPER to compute single-cell transcription factor (TF) activities from predicted TF targets.
  #'
  #' @description Compute VIPER TF activity scores using predicted TF targets and wild type (WT) and TF knockout (KO) scRNA-seq
  #' data.
  #'
  #' @param predictions.tbl data.frame. A data.frame of cell type-specific TF targets, where each row corresponds to a
  #' cell type-specific TF target, which is described by columns TF, cell.type, target, and score. TF and target are
  #' gene symbols, appearing as row names in the scRNA-seq data in sc.data. score is the strength of the interaction
  #' and should be in [-1, +1], with positive values corresponding to a positively regulated (induced) target and
  #' negative values corresponding to a negatively regulated (repressed) target.
  #' @param sc.metadata data.frame. Metadata describing the single-cell data, where each row is a cell. Row names
  #' correspond to the cell id. The cell's type is provided in column sc.cell.type.col and the KO'ed TF is in
  #' column sc.genotype.col. WT cells have gRNA_perturb set to CTRL.
  #' @param sc.data data.frame. scRNA-seq data, with row names gene symbols and column names cell ids. The data
  #' are log normalized.
  #' @param sc.cell.type.col. character string providing the name of the column in sc.metadata holding the cell type.
  #' @param sc.genotype.col. character string providing the name of the column in sc.metadata holding WT vs TF KO status.
  #' @param sc.wt.status. character string providing the status of WT cells in the sc.genotype.col
  #' @return A data.frame with VIPER TF activity scores for each cell. Each row is a cell, with VIPER TF activity score in column score.
  #' The TF is in column TF. The cell's type is in column cell.type and its WT or TF KO status
  #' is in column condition (as WT or KO, respectively).

  plyr::ddply(predictions.tbl,
        .variables = c("TF", "cell.type"),
        .parallel = FALSE,
        .fun = function(df) {
          tf <- df[1, "TF"]
          ct <- df[1, "cell.type"]

          ko.flag <- (sc.metadata[, sc.genotype.col] == tf) & (sc.metadata[, sc.cell.type.col] == ct)
          wt.flag <- (sc.metadata[, sc.genotype.col] == sc.wt.status) & (sc.metadata[, sc.cell.type.col] == ct)

          # Check if there are any cells for KO or WT conditions
          if (sum(ko.flag) == 0 || sum(wt.flag) == 0) {
            warning(paste("Skipping TF:", tf, "Celltype:", ct, "due to no KO or WT cells found for either KO or WT conditions."))
            # Return an empty data frame matching the expected output structure
            return(data.frame(score = numeric(), perturbation = character(), condition = character(), TF = character(), cell.type = character()))
          }

          ko.mat <- sc.data[, ko.flag, drop = FALSE]
          wt.mat <- sc.data[, wt.flag, drop = FALSE]

          # Ensure expression matrices are not empty after subsetting
          if (ncol(ko.mat) == 0 || ncol(wt.mat) == 0 || nrow(ko.mat) == 0 || nrow(wt.mat) == 0) {
              warning(paste("Skipping TF:", tf, "Celltype:", ct, "due to empty KO or WT expression matrix (0 rows or 0 columns)."))
              return(data.frame(score = numeric(), perturbation = character(), condition = character(), TF = character(), cell.type = character()))
          }

          combined.mat <- cbind(ko.mat, wt.mat)

          # Ensure combined.mat also has rows and columns
          if (ncol(combined.mat) == 0 || nrow(combined.mat) == 0) {
              warning(paste("Skipping TF:", tf, "Celltype:", ct, "due to empty combined expression matrix."))
              return(data.frame(score = numeric(), perturbation = character(), condition = character(), TF = character(), cell.type = character()))
          }

          # Create regulon for viper::viper
          viper_regulon <- list()
          current_tf_targets_df <- df[df$TF == tf, c("target", "score"), drop=FALSE] # Use drop=FALSE to keep as data.frame even if one row

          if (nrow(current_tf_targets_df) > 0) {
            # Filter targets to only include genes present in the expression data
            targets_in_expression <- intersect(current_tf_targets_df$target, rownames(combined.mat))
            if (length(targets_in_expression) == 0) {
                warning(paste("Skipping TF:", tf, "Celltype:", ct, "due to no targets found in expression data."))
                return(data.frame(score = numeric(), perturbation = character(), condition = character(), TF = character(), cell.type = character()))
            }
            filtered_tf_targets <- current_tf_targets_df[current_tf_targets_df$target %in% targets_in_expression, ]

            if (nrow(filtered_tf_targets) == 0) { # Should not happen if previous check passed, but double-checking
                warning(paste("Skipping TF:", tf, "Celltype:", ct, "due to no filtered targets after intersect."))
                return(data.frame(score = numeric(), perturbation = character(), condition = character(), TF = character(), cell.type = character()))
            }

            tfmode_values <- setNames(filtered_tf_targets$score, filtered_tf_targets$target)
            viper_regulon[[tf]] <- list(tfmode = tfmode_values)
          } else {
             warning(paste("Skipping TF:", tf, "Celltype:", ct, "due to no targets found for TF in predictions.tbl."))
             return(data.frame(score = numeric(), perturbation = character(), condition = character(), TF = character(), cell.type = character()))
          }

          # Add a dummy regulon if only one is present, as viper might require multiple.
          if (length(viper_regulon) < 2) {
             all_genes_in_expr <- rownames(combined.mat)
             existing_targets <- names(viper_regulon[[tf]]$tfmode)
             possible_dummy_targets <- setdiff(all_genes_in_expr, existing_targets)

             if (length(possible_dummy_targets) > 0) {
                dummy_target_gene <- sample(possible_dummy_targets, 1)
                # Use a small non-zero score for dummy TF
                viper_regulon[["DUMMY_VIPER_TF"]] <- list(tfmode = setNames(c(0.01), dummy_target_gene))
             } else {
                warning(paste("Failed to create dummy regulon for TF:", tf, "Celltype:", ct, "No suitable dummy target gene found in expression data."))
                return(data.frame(score = numeric(), perturbation = character(), condition = character(), TF = character(), cell.type = character()))
             }
          }

          # Call viper::viper
          # The traceback indicates `minsize = 0` for aREA. Let's explicitly set it.
          viper_method <- "area"
          viper_minsize <- 0 # Based on traceback showing aREA called with minsize=0

          vp_scores_matrix <- tryCatch({
            viper::viper(
              eset = combined.mat,
              regulon = viper_regulon,
              method = viper_method,
              minsize = viper_minsize,
              pleiotropy = FALSE
            )
          }, error = function(e) {
            warning(paste("viper::viper failed for TF:", tf, "Celltype:", ct, "Error:", e$message))
            return(NULL)
          })

          if (is.null(vp_scores_matrix)) {
              return(data.frame(score = numeric(), perturbation = character(), condition = character(), TF = character(), cell.type = character()))
          }

          # Extract scores for the actual TF we are analyzing
          if (!tf %in% rownames(vp_scores_matrix)) {
              warning(paste("TF", tf, "not found in VIPER output matrix for celltype", ct, "after viper::viper call."))
              return(data.frame(score = numeric(), perturbation = character(), condition = character(), TF = character(), cell.type = character()))
          }
          tf_activity_scores <- vp_scores_matrix[tf, , drop = FALSE] # ensure it remains a matrix even for single TF/cell

          # Reshape to a data frame for ddply
          res_df <- data.frame(
            score = as.numeric(tf_activity_scores),
            cell_id = colnames(tf_activity_scores),
            TF = tf,
            cell.type = ct
          )

          # Add perturbation status from sc.metadata
          all_cells_in_combined_mat_names <- colnames(combined.mat)
          relevant_metadata <- sc.metadata[all_cells_in_combined_mat_names, c(sc.genotype.col), drop = FALSE]

          res_df <- dplyr::left_join(res_df,
                                     data.frame(cell_id = rownames(relevant_metadata),
                                                perturbation_status = relevant_metadata[[sc.genotype.col]]),
                                     by = "cell_id")
          colnames(res_df)[colnames(res_df) == "perturbation_status"] <- "perturbation"

          res_df$condition <- ifelse(res_df$perturbation == sc.wt.status, "WT", "KO")

          # Remove cell_id if it's not a desired output column
          res_df$cell_id <- NULL

          return(res_df)
        })
}

compare.viper.distributions <- function(viper.df) {
  #' Compare VIPER TF activity scores between WT and TK KO cells.
  #'
  #' @description Apply a one-sided Wilcoxon test of the hypothesis that TF activity scores are higher in WT than in TF KO cells.
  #'
  #' @param viper.df data.frame. A data.frame with VIPER TF activity scores for each cell, e.g., as returned by score.viper.
  #' Each row is a cell, with VIPER TF activity score in column score. The TF is in column TF.
  #' The cell's type is in column cell.type and its WT or TF KO status is in column condition (as WT or KO, respectively).
  #' @return A data.frame with the Wilcoxon significance (column pval) that the VIPER activity score is higher for WT
  #' cells than for TF KO cells for the corresponding cell.type and TF.
  stats <-
    plyr::ddply(viper.df, .variables = c("cell.type", "TF"),
          .fun = function(df) {
            ret <- wilcox.test(x = subset(df, condition == "WT")$score,
                               y = subset(df, condition == "KO")$score, alternative="greater")
            data.frame(pval = ret$p.value)
          })
  stats <- stats[order(stats$pval, decreasing=FALSE),]
  stats
}

In [16]:
tmp <- tfs.to.analyze[, c("TF", "celltype_jf")]
colnames(tmp) <- c("TF", "cell.type")
tmp <- merge(grnboost2.res, tmp)
gb2.preds <- subset(tmp, significant == TRUE)

In [17]:
gb2.preds

      cell.type TF    target          importance cor.p        score
13    ctx_ip    ASH1L MAGIX            6.655971   0.04564888   0.2853538
25    ctx_ip    ASH1L LINC00106        6.799577   0.22468782   0.2915105
51    ctx_ip    ASH1L LINC00624        8.645615   0.21828754   0.3706535
112   ctx_ip    ASH1L MAF1             5.817008  -0.15821782  -0.2493859
130   ctx_ip    ASH1L LIAS             7.182140   0.23205567   0.3079116
220   ctx_ip    ASH1L LINC01456        7.462069   0.24993178   0.3199127
245   ctx_ip    ASH1L LINC01876        7.464188   0.33550507   0.3200036
262   ctx_ip    ASH1L NLGN1            5.989125   0.32909133   0.2567649
277   ctx_ip    ASH1L NMNAT2           5.682003   0.17801361   0.2435980
284   ctx_ip    ASH1L NOB1             5.433298  -0.05704042  -0.2329356
326   ctx_ip    ASH1L MARF1            6.268968   0.27321028   0.2687623
345   ctx_ip    ASH1L LPCAT1           6.876462  -0.16856109  -0.2948067
385   ctx_ip    ASH1L LRRC27           5.499440   0.16864617   0.2357712
387   ctx_ip    ASH1L LRRC29           6.378218   0.12683423   0.2734460
487   ctx_ip    ASH1L PCCB             7.105791   0.18808575   0.3046384
489   ctx_ip    ASH1L PCDH11X          6.139401   0.16031910   0.2632075
547   ctx_ip    ASH1L LSM14B          10.803147   0.21845748   0.4631509
593   ctx_ip    ASH1L NR3C1            5.441296   0.13287723   0.2332784
629   ctx_ip    ASH1L LINC02210-CRHR1  5.542600   0.17033708   0.2376215
649   ctx_ip    ASH1L LINC02397        6.221512   0.16162823   0.2667277
655   ctx_ip    ASH1L LINC02572        7.051614  -0.14981679  -0.3023158
681   ctx_ip    ASH1L PDP2             6.770198  -0.18702158  -0.2902509
686   ctx_ip    ASH1L PDSS2            7.526249   0.20454279   0.3226643
725   ctx_ip    ASH1L OPRM1            6.144840   0.03347816   0.2634407
729   ctx_ip    ASH1L ORAI1            5.482438   0.04162161   0.2350423
752   ctx_ip    ASH1L OSTM1            6.874579  -0.08359305  -0.2947260
753   ctx_ip    ASH1L OSTN             5.779467  -0.25276822  -0.2477764
762   ctx_ip    ASH1L OTULINL         10.289019   0.21764412   0.4411093
776   ctx_ip    ASH1L P3H2             5.719394   0.18193802   0.2452010
826   ctx_ip    ASH1L PARPBP           6.159341  -0.07283129  -0.2640624
⋮     ⋮         ⋮     ⋮               ⋮          ⋮            ⋮
57258 ge_in     MYT1L AC012615.1       8.015912   0.225215834  0.3436570
57289 ge_in     MYT1L AC019068.1       7.136363   0.035774000  0.3059491
57312 ge_in     MYT1L AC022075.1       8.946356  -0.009442213 -0.3835469
57320 ge_in     MYT1L AC022382.1       7.162987   0.149193617  0.3070905
57383 ge_in     MYT1L AC044781.1       9.392347   0.161623004  0.4026673
57392 ge_in     MYT1L AC055811.2       7.996144   0.062169170  0.3428095
57409 ge_in     MYT1L AC068286.1       7.811187   0.074430893  0.3348801
57419 ge_in     MYT1L AC069029.1       7.150838   0.078636575  0.3065697
57447 ge_in     MYT1L AC078785.1       7.033026   0.108883897  0.3015188
57461 ge_in     MYT1L AC079950.1       7.887097   0.175430273  0.3381344
57478 ge_in     MYT1L AC087623.2       9.049605   0.164560521  0.3879734
57479 ge_in     MYT1L AC087623.4      10.120812   0.106597490  0.4338980
57488 ge_in     MYT1L AC090589.2       8.133392   0.005496640  0.3486936
57495 ge_in     MYT1L AC090971.2       8.495609   0.144323246  0.3642225
57500 ge_in     MYT1L AC091132.2      10.117748   0.154349753  0.4337666
57501 ge_in     MYT1L AC091167.6       7.047430   0.114792186  0.3021364
57546 ge_in     MYT1L AC093627.5       8.696263   0.149276922  0.3728249
57552 ge_in     MYT1L AC096564.1      11.729928   0.175430273  0.5028838
57616 ge_in     MYT1L AC107068.2       8.858235   0.097742300  0.3797689
57646 ge_in     MYT1L AC114490.3       7.625939   0.084054934  0.3269381
57663 ge_in     MYT1L AC120193.1      14.947612   0.113034292  0.6408318
57696 ge_in     MYT1L AC137810.1       7.470503   0.117026474  0.3202743
57698 ge_in     MYT1L AC138305.1       7.674250   0.159849229  0.3290093
57702 ge_in     MYT1L AC139530.1       8.341285  -0.038679416 -0.3576063
57707 ge_in     MYT1L AC145422.1       9.576359   0.040124843  0.4105563
57747 ge_in     MYT1L ACOX1            7.935133   0.147842732  0.3401938
57823 ge_in     MYT1L ADIPOR1          8.049297   0.065683698  0.3450883
57883 ge_in     MYT1L AHRR             6.997097   0.171069395  0.2999785
57896 ge_in     MYT1L AK9              8.508172   0.298793250  0.3647611
57922 ge_in     MYT1L AL022097.1       7.835206   0.096281135  0.3359098
      pval         padj         significant
13    3.532427e-07 3.344856e-03 TRUE
25    2.025157e-07 1.920456e-03 TRUE
51    5.890865e-11 5.635202e-07 TRUE
112   7.306756e-06 6.844969e-02 TRUE
130   4.358096e-08 4.142371e-04 TRUE
220   1.347164e-08 1.282635e-04 TRUE
245   1.335027e-08 1.271213e-04 TRUE
262   4.046960e-06 3.803333e-02 TRUE
277   1.148678e-05 1.074129e-01 TRUE
284   2.577118e-05 2.395946e-01 TRUE
326   1.497191e-06 1.412300e-02 TRUE
345   1.496659e-07 1.420330e-03 TRUE
385   2.085428e-05 1.942994e-01 TRUE
387   1.004037e-06 9.479118e-03 TRUE
487   5.959036e-08 5.661680e-04 TRUE
489   2.384966e-06 2.246400e-02 TRUE
547   4.147723e-16 3.975178e-12 TRUE
593   2.512299e-05 2.336689e-01 TRUE
629   1.814093e-05 1.691823e-01 TRUE
649   1.777426e-06 1.675935e-02 TRUE
655   7.426244e-08 7.052704e-04 TRUE
681   2.271323e-07 2.153214e-03 TRUE
686   1.023129e-08 9.745303e-05 TRUE
725   2.339230e-06 2.203555e-02 TRUE
729   2.202549e-05 2.050793e-01 TRUE
752   1.507838e-07 1.430788e-03 TRUE
753   8.294331e-06 7.765152e-02 TRUE
762   8.825941e-15 8.455251e-11 TRUE
776   1.014391e-05 9.490642e-02 TRUE
826   2.221354e-06 2.092960e-02 TRUE
⋮     ⋮            ⋮            ⋮
57258 2.031421e-06 1.920100e-02 TRUE
57289 2.043448e-05 1.911850e-01 TRUE
57312 1.351713e-07 1.285885e-03 TRUE
57320 1.912392e-05 1.790572e-01 TRUE
57383 3.342871e-08 3.186425e-04 TRUE
57392 2.145379e-06 2.027598e-02 TRUE
57409 3.553640e-06 3.352504e-02 TRUE
57419 1.971177e-05 1.845022e-01 TRUE
57447 2.637396e-05 2.464119e-01 TRUE
57461 2.892637e-06 2.730360e-02 TRUE
57478 9.837356e-08 9.363196e-04 TRUE
57479 2.974336e-09 2.841978e-05 TRUE
57488 1.464922e-06 1.385230e-02 TRUE
57495 5.200210e-07 4.931879e-03 TRUE
57500 3.005832e-09 2.871772e-05 TRUE
57501 2.545755e-05 2.378753e-01 TRUE
57546 2.877575e-07 2.732545e-03 TRUE
57552 7.745003e-12 7.422811e-08 TRUE
57616 1.768066e-07 1.680900e-03 TRUE
57646 5.827171e-06 5.486282e-02 TRUE
57663 4.236484e-18 4.064059e-14 TRUE
57696 8.750449e-06 8.228047e-02 TRUE
57698 5.127433e-06 4.830555e-02 TRUE
57702 8.126052e-07 7.696997e-03 TRUE
57707 1.843724e-08 1.758175e-04 TRUE
57747 2.537016e-06 2.395704e-02 TRUE
57823 1.852021e-06 1.750901e-02 TRUE
57883 2.879787e-05 2.689145e-01 TRUE
57896 5.012968e-07 4.755803e-03 TRUE
57922 3.330266e-06 3.142106e-02 TRUE

In [18]:
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(c("dorothea", "decoupleR"))

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com

Bioconductor version 3.22 (BiocManager 1.30.27), R 4.5.2 (2025-10-31)

Installing package(s) 'BiocVersion', 'dorothea', 'decoupleR'

also installing the dependencies ‘formatR’, ‘BiocGenerics’, ‘lambda.r’, ‘futile.options’, ‘Biobase’, ‘futile.logger’, ‘snow’, ‘BH’, ‘bcellViper’, ‘BiocParallel’, ‘parallelly’


Old packages: 'base64enc', 'broom', 'bslib', 'cluster', 'cpp11', 'data.table',
  'DBI', 'dbplyr', 'dplyr', 'dtplyr', 'foreign', 'gargle', 'ggplot2', 'httr',
  'later', 'lattice', 'lubridate', 'openssl', 'pkgload', 'rappdirs', 'readr',
  'shiny', 'timechange', 'uuid', 'vctrs', 'viridisLite', 'vroom', 'xfun',
  'xml2', 'xtable'

In [19]:
# Explicitly install and load the 'viper' package, which is a dependency for run_viper
BiocManager::install("viper", update = FALSE, ask = FALSE, force = TRUE)
library(dorothea)
library (decoupleR)
library(viper)

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com

Bioconductor version 3.22 (BiocManager 1.30.27), R 4.5.2 (2025-10-31)

Installing package(s) 'viper'

also installing the dependencies ‘lazyeval’, ‘crosstalk’, ‘kernlab’, ‘plotly’, ‘segmented’, ‘proxy’, ‘mixtools’, ‘e1071’



Attaching package: ‘decoupleR’


The following object is masked from ‘package:dorothea’:

    run_viper


The following object is masked from ‘package:R.oo’:

    abort


The following object is masked from ‘package:data.table’:

    :=


Loading required package: Biobase

Loading required package: BiocGenerics

Loading required package: generics


Attaching package: ‘generics’


The following object is masked from ‘package:R.utils’:

    evaluate


The following object is masked from ‘package:R.oo’:

    compile


The following object is masked from ‘package:dplyr’:

    explain


The following objects are masked from ‘package:base’:

    as.difftime, as.factor, as.ordered, intersect, is.element, setdiff,
    setequal, union



Attaching package: ‘BiocGenerics’


The following object is masked from ‘package:dplyr’:

    combine


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, saveRDS, table, tapply, unique,
    unsplit, which.max, which.min


Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

In [20]:
# Compute VIPER TF activity scores for predictions using WT and TF KO scRNA-seq data

# gb2.viper <- score.viper(gb2.preds, sc.metadata, sc.data)
gb2.viper <- score.viper(gb2.preds, sc.metadata, sc.data)

Warning message in value[[3L]](cond):
“viper::viper failed for TF: ASH1L Celltype: ctx_ip Error: 'arg' should be one of “none”, “scale”, “rank”, “mad”, “ttest””
Warning message in value[[3L]](cond):
“viper::viper failed for TF: ASH1L Celltype: ge_in Error: 'arg' should be one of “none”, “scale”, “rank”, “mad”, “ttest””
Warning message in value[[3L]](cond):
“viper::viper failed for TF: BCL11A Celltype: ctx_npc Error: 'arg' should be one of “none”, “scale”, “rank”, “mad”, “ttest””
Warning message in value[[3L]](cond):
“viper::viper failed for TF: KDM5B Celltype: ge_in Error: 'arg' should be one of “none”, “scale”, “rank”, “mad”, “ttest””
Warning message in value[[3L]](cond):
“viper::viper failed for TF: KMT2A Celltype: ctx_npc Error: 'arg' should be one of “none”, “scale”, “rank”, “mad”, “ttest””
Warning message in value[[3L]](cond):
“viper::viper failed for TF: MYT1L Celltype: ge_in Error: 'arg' should be one of “none”, “scale”, “rank”, “mad”, “ttest””

In [21]:
gb2.viper

     score perturbation condition TF cell.type

In [22]:
# Filter sc.metadata for the specific cell type 'ctx_npc'
metadata_filtered_ct <- subset(sc.metadata, celltype_jf == "ctx_npc")

# Check the unique gRNA values within this filtered metadata
unique_grna_in_ctx_npc <- unique(metadata_filtered_ct$gRNA)
print(paste("Unique gRNA values for celltype 'ctx_npc':", paste(unique_grna_in_ctx_npc, collapse = ", ")))

# Check for the presence of WT (CTRL) and BCL11A KO for this cell type
is_wt_present <- "CTRL" %in% unique_grna_in_ctx_npc
is_tf_ko_present <- "BCL11A" %in% unique_grna_in_ctx_npc

if (!is_wt_present) {
  print("Warning: 'CTRL' (WT) cells are missing for celltype 'ctx_npc'.")
}
if (!is_tf_ko_present) {
  print("Warning: 'BCL11A' (KO) cells are missing for celltype 'ctx_npc'.")
}

[1] "Unique gRNA values for celltype 'ctx_npc': MECP2, BCL11A, ADNP, DEAF1, MYT1L, TBR1, SRCAP, CIC, TCF20, BAZ2B, FOXP1, ASH1L, KDM5B, KMT2A, Control2"
[1] "Warning: 'CTRL' (WT) cells are missing for celltype 'ctx_npc'."

In [23]:
# Filter predictions to focus on BCL11A
gb2.preds.BCL11A <- subset(gb2.preds, TF == "BCL11A")

# Recompute VIPER TF activity scores for BCL11A predictions
gb2.viper.BCL11A <- score.viper(gb2.preds.BCL11A, sc.metadata, sc.data,
                                 sc.cell.type.col = "celltype_jf",
                                 sc.genotype.col = "gRNA")

# Display the results for BCL11A
gb2.viper.BCL11A

Warning message in .fun(piece, ...):
“Skipping TF: BCL11A Celltype: ctx_npc due to no KO or WT cells found for either KO or WT conditions.”

     score perturbation condition TF cell.type